### ISSUE TITLE
Too many duplicates

### ISSUE THREAD

**Issue by b8vr** [MrGITit/Wordlist-Zombie#3]
I've tried the tools on some different small wordlists, but when I run sort | uniq afterwards it's shrinked by something like 80%, suggesting a rather large output of duplicates.

**Comment by PhillyStyle** [comment]
Thanks for the feedback.  I could maybe add some options to relax the weights a little or something.  But I think you will have more luck on larger wordlists.

**Comment by PhillyStyle** [comment]
Added options --unweighted, and --halfweighted to Wordlist Generator to help solve problem with too many duplicates.  Also fixed a bug with the wordlist generation that could have contributed to too many duplicates.  We will call this issue addressed for now.
